---
title: "Aug 27"
output:
  html_document: default
  pdf_document: default
---

```{r echo=FALSE, include=FALSE}
library(mvtnorm)
library(tableone)
library(parallel)
library(rstan)
library(loo)
library(gamm4)
library(Hmisc)
library(FactoMineR)
library(nFactors)
library(reshape2)
library(psych)
library(data.table)
library(mice)
library(abind)
library(cvTools)
library(modEvA)
require(knitr)
require(tidyverse)
knitr::opts_chunk$set(echo = TRUE)

```

```{r}

nda18 <- readRDS("E:/ABCD study/R/Outputs/2019-08-27_nda18_b1_voi.Rds")

```




```{r}

# premature
nda18$premature <- nda18$devhx_12a_born_premature_p
levels(nda18$premature) <- list("Yes" = "Yes",
                                "No" = "No")

table(nda18$premature)


```



```{r}
## Select demographics


ind_demog = c(
  which(names(nda18) == "age"),
  which(names(nda18) == "female"),
  which(names(nda18) == "race.ethnicity.5level.imputed"),
  which(names(nda18) == "race.eth.8level.imputed"),
  which(names(nda18) == "high.educ.imputed"),
  which(names(nda18) == "household.income.3level.imputed"),
  which(names(nda18) == "household.income.4level.imputed"),
  which(names(nda18) == "married.imputed"))
  
names(nda18)[ind_demog]
summary(nda18[, ind_demog])

```

```{r}
## Select nesting variables

ind_nest = c(which(names(nda18) == "abcd_site"), which(names(nda18) == "rel_family_id"))

summary(nda18[, ind_nest])
nda18$abcd_site = as.character(nda18$abcd_site)
nda18$abcd_site[nda18$abcd_site == "site22"] = "site07"
nda18$abcd_site = factor(nda18$abcd_site)
```


```{r}
## Select neuropsychological measures
ind_pea_ravlt = c(
  which(names(nda18) == "pea_ravlt_sd_trial_i_tc.imputed"),
  which(names(nda18) == "pea_ravlt_sd_trial_ii_tc.imputed"),
  which(names(nda18) == "pea_ravlt_sd_trial_iii_tc.imputed")
  ,
  which(names(nda18) == "pea_ravlt_sd_trial_iv_tc.imputed"),
  which(names(nda18) == "pea_ravlt_sd_trial_v_tc.imputed")
)


names(nda18)[ind_pea_ravlt]
```
```{r}
summary(nda18[,ind_pea_ravlt])

```


```{r}
nda18$pea_ravlt_ld.imputed = apply(nda18[, ind_pea_ravlt], 1, sum)

par(mfrow = c(1, 2))
hist(nda18$pea_ravlt_ld.imputed)
hist(nda18$lmt_scr_perc_correct.imputed)
```
```{r}
ind_np = c(which(names(nda18)=="nihtbx_picvocab_uncorrected.imputed"),
           which(names(nda18)=="nihtbx_flanker_uncorrected.imputed"),
           which(names(nda18)=="nihtbx_list_uncorrected.imputed"),
           which(names(nda18)=="nihtbx_cardsort_uncorrected.imputed"),
           which(names(nda18)=="nihtbx_pattern_uncorrected.imputed"),
           which(names(nda18)=="nihtbx_picture_uncorrected.imputed"),
           which(names(nda18)=="nihtbx_reading_uncorrected.imputed"),
           which(names(nda18)=="pea_ravlt_ld.imputed"),
           which(names(nda18)=="lmt_scr_perc_correct.imputed")
           ,which(names(nda18)=="pea_ravlt_sd_trial_vi_tc.imputed"),
           which(names(nda18)=="pea_ravlt_ld_trial_vii_tc.imputed"),
           which(names(nda18)=="pea_wiscv_tss.imputed")
)


names(nda18)[ind_np]


```

```{r}
## Select dependent measures 
ind_dv = c(
  which(names(nda18) == "cbcl_scr_syn_external_r"),
  which(names(nda18) == "cbcl_scr_syn_internal_r"),
  which(names(nda18) == "cbcl_scr_07_stress_r")
)

names(nda18)[ind_dv]
```

```{r}

######################
######################
## Rename variables ##
######################
######################

names(nda18)[which(names(nda18) == "age")] = "Age"
nda18$Age = nda18$Age / 12
names(nda18)[which(names(nda18) == "female")] = "Female"
names(nda18)[which(names(nda18) == "race.ethnicity.5level.imputed")] = "Race Ethnicity"
names(nda18)[which(names(nda18) == "high.educ.imputed")] = "Highest Parental Education"
names(nda18)[which(names(nda18) == "married.imputed")] = "Household Marital Status"
names(nda18)[which(names(nda18) == "household.income.4level.imputed")] = "Household Income"
names(nda18)[which(names(nda18) == "abcd_site")] = "Site"
names(nda18)[which(names(nda18) == "rel_relationship")] = "Relationship"
names(nda18)[which(names(nda18) == "premature")] = "Premature"
names(nda18)[which(names(nda18) == "devhx_3_age_at_birth_mother_p")] = "Age of Mother"


# names(nda18)[which(names(nda18)=="nihtbx_picvocab_uncorrected")] = "PicVocab"
# names(nda18)[which(names(nda18)=="nihtbx_flanker_uncorrected")] = "Flanker"
# names(nda18)[which(names(nda18)=="nihtbx_list_uncorrected")] = "List"
# names(nda18)[which(names(nda18)=="nihtbx_cardsort_uncorrected")] = "CardSort"
# names(nda18)[which(names(nda18)=="nihtbx_pattern_uncorrected")] = "Pattern"
# names(nda18)[which(names(nda18)=="nihtbx_picture_uncorrected")] = "Picture"
# names(nda18)[which(names(nda18)=="nihtbx_reading_uncorrected")] = "Reading"
# names(nda18)[which(names(nda18)=="pea_ravlt_ld")] = "RAVLT"
# names(nda18)[which(names(nda18)=="lmt_scr_perc_correct")] = "LMT"
# names(nda18)[which(names(nda18)=="pea_wiscv_tss")] = "WISC-V"
# names(nda18)[which(names(nda18)=="cbcl_scr_syn_external_r")] = "Externalizing"
# names(nda18)[which(names(nda18)=="cbcl_scr_syn_internal_r")] = "Internalizing"
# names(nda18)[which(names(nda18)=="cbcl_scr_07_stress_r")] = "Stress"

nda18$compl = "Incomplete"
nda18$compl[complete.cases(nda18[, c(ind_nest, ind_np)])] = "Complete"
names(nda18)[c(ind_nest, ind_np)]
table(nda18$compl)



```

```{r}
## Create Table 1
vars1 <-
  c(
    "Age",
    "Female",
    "Race Ethnicity",
    "Highest Parental Education",
    "Household Marital Status",
    "Household Income",
    "Relationship",
    "Site",
    "Premature",
    "Age of Mother"
  )
tab1 <- CreateTableOne(vars = vars1,
                       data = nda18)
tabAsStringMatrix <-
  print(tab1, printToggle = FALSE, noSpaces = TRUE)
tab1 = knitr::kable(tabAsStringMatrix)
kable(tabAsStringMatrix)

```


```{r}
## Create Table 2
# vars2 <- c("PicVocab", "Flanker", "List", "CardSort", "Pattern",
#             "Picture","Reading","RAVLT","WISC-V",
#             "LMT","Externalizing","Internalizing","Stress")

vars2 <- c(
  "pea_ravlt_ld.imputed",
  'pea_ravlt_ld_trial_vii_tc.imputed',
  'pea_ravlt_sd_trial_vi_tc.imputed',
  "nihtbx_list_uncorrected.imputed",
  "nihtbx_reading_uncorrected.imputed",
  "nihtbx_picvocab_uncorrected.imputed",
  "nihtbx_cardsort_uncorrected.imputed",
  "nihtbx_picture_uncorrected.imputed",
  "pea_wiscv_tss.imputed",
  "nihtbx_flanker_uncorrected.imputed",
  "lmt_scr_perc_correct.imputed",
  "nihtbx_pattern_uncorrected.imputed"
)


tab2 <- CreateTableOne(vars = vars2,
                       data = nda18)
tabAsStringMatrix <-
  print(tab2, printToggle = FALSE, noSpaces = TRUE)
tab2 = knitr::kable(tabAsStringMatrix)
kable(tabAsStringMatrix )
```


```{r}

## Create SM Figures 1 & 2
par(mfrow = c(3, 3))
for (p in 1:12) {
  hist(
    scale(nda18[, ind_np[p]]),
    xlab = "",
    freq = FALSE,
    main = names(nda18)[ind_np][p]
  )
}

```
```{r}

par(mfrow = c(2, 2))
for (p in 1:3) {
  hist(
    scale(nda18[, ind_dv[p]]),
    xlab = "",
    freq = FALSE,
    main = names(nda18)[ind_dv][p]
  )
}

```

```{r}
###################################
###################################
## Subset variables for analyses ##
###################################
###################################

data = nda18[, c(
  1,
  ind_nest,
  ind_demog,
  which(names(nda18) == "rel_relationship"),
  which(names(nda18) == "rel_group_id"),
  ind_np,
  ind_dv
)]
names(data)
dim(data)
data$src_subject_id = as.character(data$src_subject_id)
names(data)[names(data) == "src_subject_id"] = "pid"
data$site_num = as.numeric(substr(data$Site, 5, 6))
data$fam_num = 0
ind = 0
for (i in sort(unique(data$rel_family_id))) {
  ind = ind + 1
  data$fam_num[data$rel_family_id == i &
                 !is.na(data$rel_family_id)] = ind
}
data = data[order(data$site_num, data$fam_num, data$rel_group_id), ]

```

```{r}
ind_Y = c(13:24)
names(data)[ind_Y]
```

```{r}

####################
####################
## Fit usual PCA  ## 
####################
####################

## PCA on unimputed data 

Y = as.matrix(scale(data[complete.cases(data[, c(ind_Y)]), ind_Y]))
ev = eigen(cor(Y))
ap = parallel(
  subject = nrow(Y),
  var = ncol(Y),
  rep = 100,
  cent = .05
)
nS = nScree(x = ev$values, aparallel = ap$eigen$qevpea)
plotnScree(nS)
ncomp = 3

```

```{r}
y.pca = psych::principal(Y,
                         rotate = "promax",
                         nfactors = ncomp,
                         scores = TRUE)
y.pca$loadings

```

```{r}
y.pca = psych::principal(Y,
                         rotate = "varimax",
                         nfactors = ncomp,
                         scores = TRUE)
y.pca$loadings
```

